//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FritzenSpeechApp.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FritzenSpeechApp.Lang.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce other sounds when spoking.
        /// </summary>
        public static string setup_audio_mixer {
            get {
                return ResourceManager.GetString("setup_audio_mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warn] If this app craches, system audio is manteined reduced.
        /// </summary>
        public static string setup_audio_mixer_help {
            get {
                return ResourceManager.GetString("setup_audio_mixer_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string setup_flags {
            get {
                return ResourceManager.GetString("setup_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display focus when speech starts.
        /// </summary>
        public static string setup_focus {
            get {
                return ResourceManager.GetString("setup_focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize Selected Voice (native voice).
        /// </summary>
        public static string setup_grid_prioritize_selected_voice {
            get {
                return ResourceManager.GetString("setup_grid_prioritize_selected_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice List (Priority ordered).
        /// </summary>
        public static string setup_grid_title {
            get {
                return ResourceManager.GetString("setup_grid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string setup_grid_voice_gender {
            get {
                return ResourceManager.GetString("setup_grid_voice_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string setup_grid_voice_language {
            get {
                return ResourceManager.GetString("setup_grid_voice_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string setup_grid_voice_name {
            get {
                return ResourceManager.GetString("setup_grid_voice_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speek Speed.
        /// </summary>
        public static string setup_grid_voice_speed {
            get {
                return ResourceManager.GetString("setup_grid_voice_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select text in any program that allows you to copy text and select an F1 shortcut key. The text will be read automatically, respecting the selected language and a voice frequency..
        /// </summary>
        public static string setup_help_text {
            get {
                return ResourceManager.GetString("setup_help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string setup_section_config {
            get {
                return ResourceManager.GetString("setup_section_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it Works?.
        /// </summary>
        public static string setup_section_help {
            get {
                return ResourceManager.GetString("setup_section_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Key.
        /// </summary>
        public static string setup_shortcut_key {
            get {
                return ResourceManager.GetString("setup_shortcut_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        public static string setup_start_minimized {
            get {
                return ResourceManager.GetString("setup_start_minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string setup_volume {
            get {
                return ResourceManager.GetString("setup_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string toolbar_pause {
            get {
                return ResourceManager.GetString("toolbar_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string toolbar_play {
            get {
                return ResourceManager.GetString("toolbar_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string toolbar_setup {
            get {
                return ResourceManager.GetString("toolbar_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string toolbar_stop {
            get {
                return ResourceManager.GetString("toolbar_stop", resourceCulture);
            }
        }
    }
}
